#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

if [ -z $1 ]
then
    echo "Enter password" 1>&2
    exit 1;
else
	if [ -f "$SCRIPTPATH/authData.yaml" ]
	then
		while read -r line ; do
			name=`echo $line | awk -F "=" '{print $1}'`
			val=`echo $line | awk -F "=" '{print $2}'`
			export "$name"="$val"
		done < "$SCRIPTPATH/authData.yaml"
	else
		source "$SCRIPTPATH/setup" -p "$1"
	fi
	
      kubectl delete -f "$SCRIPTPATH/manifests/ingress-controller.yaml"
	
	export TF_VAR_registry_password_ecr="fake"
	source "$SCRIPTPATH/stop"
	cd "$SCRIPTPATH"
    source "$SCRIPTPATH/setup" -u "$1"
fi
