#!/bin/bash

SCRIPT1=$(readlink -f "$0")
SCRIPTPATH1=$(dirname "$SCRIPT1")

deploy_module () {
    cd "$SCRIPTPATH1/../$1"
    sed -e "s/<lock_table>/$TF_VAR_lock_table/g" -e "s/<state_bucket>/$TF_VAR_state_bucket/g" -e "s+<lock_file>+$TF_VAR_project_name/$1+g" -e "s/<region>/$TF_VAR_main_region/g" "$SCRIPTPATH1/../move_remote.tf" > "$SCRIPTPATH1/../$1/state.tf"
    terraform init -migrate-state -force-copy
    terraform validate
    terraform apply -auto-approve
}

cp "$SCRIPTPATH1/../move_local.tf" "$SCRIPTPATH1/../terraform-state/state.tf"

cd "$SCRIPTPATH1/../terraform-state"

terraform init -migrate-state -force-copy
terraform validate
terraform apply -auto-approve

sed -e "s/<lock_table>/$TF_VAR_lock_table/g" -e "s/<state_bucket>/$TF_VAR_state_bucket/g" -e "s/<region>/$TF_VAR_main_region/g" "$SCRIPTPATH1/../move_remote_state.tf" > "$SCRIPTPATH1/../terraform-state/state.tf"

terraform init -migrate-state -force-copy
terraform validate
terraform apply -auto-approve

cd "$SCRIPTPATH1"

deploy_module "terraform-ecr"

cd "$SCRIPTPATH1"

echo "$(aws ecr get-login-password --region $TF_VAR_main_region)" > tmp_ecr_cred

echo "$(aws sts get-caller-identity --query Account --output text).dkr.ecr.${TF_VAR_main_region}.amazonaws.com/test-app" > tmp_ecr