#!/bin/bash

SCRIPT1=$(readlink -f "$0")
SCRIPTPATH1=$(dirname "$SCRIPT1")

deploy_module () {
    cd "$SCRIPTPATH1/../$1"
    sed -e "s/<lock_table>/$TF_VAR_lock_table/g" -e "s/<state_bucket>/$TF_VAR_state_bucket/g" -e "s+<lock_file>+$TF_VAR_project_name/$1+g" -e "s/<region>/$TF_VAR_main_region/g" "$SCRIPTPATH1/../move_remote.tf" > "$SCRIPTPATH1/../$1/state.tf"
    terraform init -migrate-state -force-copy
    terraform validate
    terraform apply -auto-approve
}

deploy_module "terraform-eks"

aws eks --region $(terraform output -raw region) update-kubeconfig \
    --name $(terraform output -raw cluster_name)

export TF_VAR_cluster_vpc="$(terraform output -raw vpc_id)"
export TF_VAR_subnets="$(terraform output -json vpc_subnets)"

deploy_module "terraform-nlb"

export NLB_EP=$(terraform output -raw nlb_dns)

cd "$SCRIPTPATH1"