#!/bin/bash

SCRIPT1=$(readlink -f "$0")
SCRIPTPATH1=$(dirname "$SCRIPT1")

cd "$SCRIPTPATH1/../terraform-eks"

terraform init -migrate-state -force-copy
terraform validate
terraform apply -auto-approve

aws eks --region $(terraform output -raw region) update-kubeconfig \
    --name $(terraform output -raw cluster_name)

export TF_VAR_cluster_vpc="$(terraform output -raw vpc_id)"
export TF_VAR_subnets="$(terraform output -json vpc_subnets)"

cd "$SCRIPTPATH1/../terraform-nlb"

terraform init -migrate-state -force-copy
terraform validate
terraform apply -auto-approve

export NLB_EP=$(terraform output -raw region)

cd "$SCRIPTPATH1"