#!/bin/bash

SCRIPT1=$(readlink -f "$0")
SCRIPTPATH1=$(dirname "$SCRIPT1")

cd "$SCRIPTPATH1/../terraform-eks"

terraform init -migrate-state -force-copy
terraform validate
terraform apply -auto-approve

aws eks --region $(terraform output -raw region) update-kubeconfig \
    --name $(terraform output -raw cluster_name)

cd "$SCRIPTPATH1"