#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd "$SCRIPTPATH/../terraform-nlb"

terraform apply -destroy -auto-approve

cd "$SCRIPTPATH/../terraform-eks"

terraform apply -destroy -auto-approve

cd "$SCRIPTPATH/../terraform-ecr"

terraform apply -destroy -auto-approve