apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {username}
  namespace: {username}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {username}-rb
  namespace: {username}
subjects:
  - kind: ServiceAccount
    name: {username}-sa
    namespace: shared
roleRef:
  kind: Role
  name: {username}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {username}-watch-rb
subjects:
  - kind: ServiceAccount
    name: {username}-sa
    namespace: shared
roleRef:
  kind: ClusterRole
  name: user-watch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {username}-sa
  namespace: shared
secrets:
  - name: {username}-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: {username}-secret
  namespace: shared
  annotations:
    kubernetes.io/service-account.name: {username}-sa
type: kubernetes.io/service-account-token